game:
  min_players: 2
  max_players: 8
  max_races: 8
  race_start_time_ms: 3000
  max_time_per_race_ms: 600000
  max_npcs: 30

car:
  max_speed: 10000
  max_life: 1000
  max_nitro: 500

  acceleration_upgrade_factor: 1.15
  handling_upgrade_factor: 1.3
  nitro_upgrade_factor: 1.1
  life_upgrade_factor: 1.5
  brake_upgrade_factor: 1.15
  mass_upgrade_factor: 0.9

  nitro_consumption: 5
  nitro_recharge_rate: 2
  boost_factor: 2.5

  hitter_factor: 0.2
  hitted_factor: 0.1

  spawn_position: [300.0, 300.0]

workshop:
  acceleration_price: 30
  handling_price: 10
  nitro_price: 40
  life_price: 25
  mass_price: 25
  brake_price: 25